batman_version: "2026.2"
node_exporter_version: "1.12.1"
bootstrap_version: "5.3.8"
meshviewer_version: "13.2.0"
alertmanager_version: "0.34.0"
alertmanager_checksum: "19c75a11d8c03dc4ade7abdbddfb3a8f28c9e7b000d0849cda0cd71dffd74a03"
