- name: Install nginx and unzip
  ansible.builtin.apt:
    name: ["nginx", "unzip"]

- name: Copy httpasswd
  ansible.builtin.copy:
    src: files/htpasswd
    dest: /etc/nginx/htpasswd
    mode: '0600'
    owner: www-data
    group: www-data

- name: Copy nginx config
  ansible.builtin.template:
    src: templates/gw-status.conf
    dest: /etc/nginx/sites-available/
    mode: '0600'
    owner: root
    group: root

- name: Enable nginx gw-status config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/gw-status.conf
    dest: /etc/nginx/sites-enabled/gw-status.conf
    owner: root
    group: root
    state: link

- name: Delete default config
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Create directory for info page
  ansible.builtin.file:
    path: /var/www/gw-status
    state: directory
    mode: '0744'
    owner: www-data
    group: www-data

- name: Scan for old bootstrap folders
  ansible.builtin.find:
    paths: /var/www/gw-status
    patterns: 'bootstrap-*'
    file_type: directory
    recurse: no
  register: bootstrap_files

- name: Remove old bootstrap folders
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ bootstrap_files.files }}"
  loop_control:
    loop_var: item
  when: "'bootstrap-' + bootstrap_version + '-dist' not in item.path"

- name: Check if bootstrap is already downloaded
  ansible.builtin.stat:
    path: /var/www/gw-status/bootstrap-{{ bootstrap_version }}-dist
  register: bootstrap_zip

- name: Download bootstrap
  ansible.builtin.get_url:
    url: "https://github.com/twbs/bootstrap/releases/download/v{{ bootstrap_version }}/bootstrap-{{ bootstrap_version }}-dist.zip"
    dest: /var/www/gw-status/bootstrap-{{ bootstrap_version }}-dist.zip
    mode: '0644'
    owner: root
    group: root
  when: not bootstrap_zip.stat.exists

- name: Unpack bootstrap
  ansible.builtin.unarchive:
    src: /var/www/gw-status/bootstrap-{{ bootstrap_version }}-dist.zip
    dest: /var/www/gw-status/
    remote_src: true
    mode: '0744'
    owner: www-data
    group: www-data
  when: not bootstrap_zip.stat.exists

- name: Delete archive
  ansible.builtin.file:
    path: /var/www/gw-status/bootstrap-{{ bootstrap_version }}-dist.zip
    state: absent
  when: not bootstrap_zip.stat.exists

- name: Copy info page
  ansible.builtin.template:
    src: templates/index.html
    dest: /var/www/gw-status/index.html
    mode: '0744'
    owner: www-data
    group: www-data

- name: Copy css
  ansible.builtin.copy:
    src: files/cover.css
    dest: /var/www/gw-status/cover.css
    mode: '0744'
    owner: www-data
    group: www-data

- name: Restart nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
