- name: Install nginx and unzip
  ansible.builtin.apt:
    name: ["nginx", "unzip"]

- name: Copy httpasswd
  ansible.builtin.copy:
    src: files/htpasswd
    dest: /etc/nginx/htpasswd
    mode: '0600'
    owner: www-data
    group: www-data

- name: Copy nginx config
  ansible.builtin.template:
    src: templates/gw-status.conf
    dest: /etc/nginx/sites-available/
    mode: '0600'
    owner: root
    group: root

- name: Enable nginx gw-status config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/gw-status.conf
    dest: /etc/nginx/sites-enabled/gw-status.conf
    owner: root
    group: root
    state: link

- name: Delete default config
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Create directory for info page
  ansible.builtin.file:
    path: /var/www/gw-status
    state: directory
    mode: '0744'
    owner: www-data
    group: www-data

- name: Dowload bootstrap
  ansible.builtin.get_url:
    url: "https://github.com/twbs/bootstrap/releases/download/v{{ bootstrap_version }}/bootstrap-{{ bootstrap_version }}-dist.zip"
    dest: /var/www/gw-status/bootstrap-{{ bootstrap_version }}-dist.zip

- name: Unpack bootstrap
  ansible.builtin.unarchive:
    src: /var/www/gw-status/bootstrap-{{ bootstrap_version }}-dist.zip
    dest: /var/www/gw-status/
    remote_src: True
    mode: '0744'
    owner: www-data
    group: www-data

- name: Delete archive
  ansible.builtin.file:
    dest: /var/www/gw-status/bootstrap-{{ bootstrap_version }}-dist.zip
    state: absent

- name: copy info page
  ansible.builtin.template:
    src: templates/index.html
    dest: /var/www/gw-status/index.html
    mode: '0744'
    owner: www-data
    group: www-data

- name: copy css
  ansible.builtin.copy:
    src: files/cover.css
    dest: /var/www/gw-status/cover.css
    mode: '0744'
    owner: www-data
    group: www-data

- name: Restart nginx service
  systemd:
    name: nginx
    state: restarted