gateways:
  hosts:
    barnitz:
      ansible_ssh_host: 195.201.117.146
      external_ipv4: 195.201.117.146
      external_interface: eth0
      ffsh_ipv4_space: 10.144.48.0/20
      ffsh_map_name: GW_Barnitz
      ffsh_ipv6_address: fddf:0bf7:80::48:1
      ffsh_ipv4_address: 10.144.48.1
      dhcp_range: 10.144.48.2-10.144.63.254
      ffsh_bat_mac: 00:5b:27:80:00:48
      ffsh_fastd_mac: 00:5b:27:80:00:48
      enable_wireguard_exit: true
      owner: ulf
    beste:
      ansible_ssh_host: 159.69.122.154
      external_ipv4: 159.69.122.154
      external_interface: eth0
      ffsh_ipv4_space: 10.144.64.0/20
      ffsh_map_name: GW_Beste
      ffsh_ipv6_address: fddf:0bf7:80::64:1
      ffsh_ipv4_address: 10.144.64.1
      dhcp_range: 10.144.64.2-10.144.79.254
      ffsh_bat_mac: 00:5b:27:80:00:64
      ffsh_fastd_mac: 00:5b:27:80:00:64
      enable_wireguard_exit: true
      owner: ulf
    bille: 
      ansible_ssh_host: 5.181.50.231
      external_ipv4: 5.181.50.231
      external_interface: eth0
      ffsh_ipv4_space: 10.144.80.0/20
      ffsh_map_name: GW_Bille
      ffsh_ipv6_address: fddf:0bf7:80::80:1
      ffsh_ipv4_address: 10.144.80.1
      dhcp_range: 10.144.80.2-10.144.95.254
      ffsh_bat_mac: 00:5b:27:80:00:80
      ffsh_fastd_mac: 00:5b:27:80:00:80
      enable_wireguard_exit: true
      owner: felix
    brunsbach:
      ansible_ssh_host: 37.221.192.238
      external_ipv4: 37.221.192.238
      external_interface: eth0
      ffsh_ipv4_space: 10.144.96.0/20
      ffsh_map_name: GW_Brunsbach
      ffsh_ipv6_address: fddf:0bf7:80::96:1
      ffsh_ipv4_address: 10.144.96.1
      dhcp_range: 10.144.96.2-10.144.111.254
      ffsh_bat_mac: 00:5b:27:80:00:96
      ffsh_fastd_mac: 00:5b:27:80:00:96
      enable_wireguard_exit: true
      owner: benjamin
    heilsau: 
      ansible_ssh_host: 95.216.157.253
      external_ipv4: 95.216.157.253
      external_interface: eth0
      ffsh_ipv4_space: 10.144.112.0/20
      ffsh_map_name: GW_Heilsau
      ffsh_ipv6_address: fddf:0bf7:80::112:1
      ffsh_ipv4_address: 10.144.112.1
      dhcp_range: 10.144.112.2-10.144.127.254
      ffsh_bat_mac: 00:5b:27:80:01:12
      ffsh_fastd_mac: 00:5b:27:80:01:12
      enable_wireguard_exit: true
      owner: ulf
    sylsbek:
      ansible_ssh_host: 195.128.103.225
      external_ipv4: 195.128.103.225
      external_interface: eth0
      ffsh_ipv4_space: 10.144.192.0/20
      ffsh_map_name: GW_Sylsbek
      ffsh_ipv6_address: fddf:0bf7:80::192:1
      ffsh_ipv4_address: 10.144.192.1
      dhcp_range: 10.144.192.2-10.144.207.254
      ffsh_bat_mac: 00:5b:27:80:01:92
      ffsh_fastd_mac: 00:5b:27:80:01:92
      enable_wireguard_exit: true
      owner: ulf
    trave: 
      ansible_ssh_host: 88.99.86.15
      external_ipv4: 88.99.86.15
      external_interface: eth0
      ffsh_ipv4_space: 10.144.208.0/20
      ffsh_map_name: GW_Trave
      ffsh_ipv6_address: fddf:0bf7:80::208:1
      ffsh_ipv4_address: 10.144.208.1
      dhcp_range: 10.144.208.2-10.144.223.254
      ffsh_bat_mac: 00:5b:27:80:02:08
      ffsh_fastd_mac: 00:5b:27:80:02:08
      enable_wireguard_exit: true
      owner: ulf
  vars:
    ansible_user: root
