- hosts: all
  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
  roles:
    - { role: network, tags: "network"}
    - { role: batman-adv, tags: "batman-adv", batman_version: "2020.4"}

#    - name: Firewall
#      copy:
#        src: configs/firewall/
#        dest: /etc/network/iptables.up.rules