- hosts: all
  vars:
    users:
      - username: root
  pre_tasks:
  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes
  roles:
    - { role: network, tags: "network"}
    - { role: wireguardexit, tags: "wireguard, exit"}
    - { role: hostname, tags: "hostname"}
    - { role: fail2ban, tags: "fail2ban"}
    - { role: batman, tags: "batman-adv", batman_version: "2022.0"}
    - { role: fastd, tags: "fastd", fastd_target: "fastd 21"}
    - { role: radvd, tags: "radvd"}
    - { role: dhcp, tags: "isc-dhcp4-server"}
    - { role: bind, tags: "dns"}
    - { role: respondd, tags: "respondd"}
    - { role: prometheus, tags: "node_exporter", node_exporter_version: "1.3.1"}
    - { role: nginx, tags: "node_exporter, nginx", bootstrap_version: "5.1.3"}
    - { role: tools, tags: "admin-tools", batman_version: "2022.0"}
    - { role: motd, tags: "motd"}
    - { role: ohmyzsh, tags: "oh-my-zsh", oh_my_zsh_theme: ffsh}
    - { role: ohmyzshtheme, tags: "oh-my-zsh-theme"}
    - { role: ssh, tags: "ssh keys", login_user: 'root'}
    - { role: ffshmon, tags: "wireguard, ffshmon"}
