- hosts: all
  vars:
    users:
      - username: root
  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
  roles:
    - { role: network, tags: "network"}
    - { role: batman, tags: "batman-adv", batman_version: "2020.4"}
    - { role: fastd, tags: "fastd", fastd_target: "fastd 21"}
    - { role: radvd, tags: "radvd"}
    - { role: bind, tags: "dns"}
    - { role: motd, tags: "motd"}
    - { role: ohmyzsh, tags: "oh-my-zsh"}

#    - name: Firewall
#      copy:
#        src: configs/firewall/
#        dest: /etc/network/iptables.up.rules