- hosts: all
  vars:
    users:
      - username: root
  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
  roles:
    - { role: network, tags: "network"}
    - { role: batman, tags: "batman-adv", batman_version: "2021.1"}
    - { role: fastd, tags: "fastd", fastd_target: "fastd 21"}
    - { role: radvd, tags: "radvd"}
    - { role: dhcp, tags: "isc-dhcp4-server"}
    - { role: bind, tags: "dns"}
    - { role: respondd, tags: "respondd"}
    - { role: prometheus, tags: "node_exporter", node_exporter_version: "1.1.2"}
    - { role: tools, tags: "admin-tools", batman_version: "2021.1"}
    - { role: motd, tags: "motd"}
    - { role: ohmyzsh, tags: "oh-my-zsh"}

#    - name: Firewall
#      copy:
#        src: configs/firewall/
#        dest: /etc/network/iptables.up.rules