- name: Deploy Gateway
  hosts: all
  vars:
    users:
      - username: root
    batman_version: "2025.0"
    node_exporter_version: "1.9.1"
    bootstrap_version: "5.3.5"
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
  roles:
    - { role: network, tags: "network"}
    - { role: wireguardexit, tags: "wireguard, exit"}
    - { role: ffshmon, tags: "wireguard, ffshmon"}
    - { role: hostname, tags: "hostname"}
    - { role: fail2ban, tags: "fail2ban"}
    - { role: batman, tags: "batman-adv"}
    - { role: fastd, tags: "fastd"}
    - { role: radvd, tags: "radvd"}
    - { role: dhcp, tags: "isc-dhcp4-server"}
    - { role: bind, tags: "dns"}
    - { role: respondd, tags: "respondd"}
    - { role: prometheus, tags: "node_exporter"}
    - { role: letsencrypt, tags: "letsencrypt"}
    - { role: nginx, tags: "node_exporter, nginx", }
    - { role: tools, tags: "admin-tools"}
    - { role: motd, tags: "motd"}
    - { role: ohmyzsh, tags: "oh-my-zsh"}
    - { role: ohmyzshtheme, tags: "oh-my-zsh"}
    - { role: ssh, tags: "ssh keys"}
