- name: Register letsencrypt account
  ansible.builtin.command: certbot register --no-eff-email -m noc@freifunk-suedholstein.de --agree-tos
- name: Restart NGINX
  ansible.builtin.systemd:
    name: nginx
    state: stopped
- name: Register Certificate
  ansible.builtin.shell: >
    certbot certonly --standalone -d {{ inventory_hostname }}.freifunk-suedholstein.de
- name: Restart NGINX
  ansible.builtin.systemd:
    name: nginx
    state: restarted
- name: Restart and Reload certbot
  ansible.builtin.systemd:
    name: certbot
    enabled: true
    daemon_reload: true
