---
- name: Install fastfetch
  ansible.builtin.apt:
    pkg: [ "fastfetch" ]
    state: present

- name: Create fastfetch config directory
  ansible.builtin.file:
    path: /root/.config/fastfetch
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy logo
  ansible.builtin.copy:
    src: files/ffsh-logo.txt
    dest: /root/.config/fastfetch/ffsh-logo.txt
    owner: root
    group: root
    mode: "0644"
- name: Adjust fastfetch config
  ansible.builtin.template:
    src: templates/config.jsonc
    dest: /root/.config/fastfetch/config.jsonc
    owner: root
    group: root
    mode: "0644"
- name: Set motd header
  ansible.builtin.copy:
    src: files/00-header
    dest: /etc/update-motd.d/00-header
    owner: root
    group: root
    mode: "0744"
- name: Remove /etc/motd
  ansible.builtin.file:
    path: /etc/motd
    state: absent
