---
- name: Install neofetch
  ansible.builtin.apt:
    pkg: ['neofetch']
    state: present
  notify: First run neofetch

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Copy logo
  ansible.builtin.copy:
    src: files/ffsh-logo.txt
    dest: /root/.config/neofetch/ffsh-logo.txt
    owner: root
    group: root
    mode: '0644'
- name: Adjust neofetch config
  ansible.builtin.template:
    src: templates/config.conf
    dest: /root/.config/neofetch/config.conf
    owner: root
    group: root
    mode: '0644'
- name: Set motd header
  ansible.builtin.copy:
    src: files/00-header
    dest: /etc/update-motd.d/00-header
    owner: root
    group: root
    mode: '0744'
- name: Remove /etc/motd
  ansible.builtin.file:
    path: /etc/motd
    state: absent
