- name: Install curl
  ansible.builtin.apt:
    name: ['curl']
- name: Clone ffshmon repository
  ansible.builtin.git:
    repo: https://github.com/ffsh/ffshmon.git
    dest: /opt/ffshmon
    force: true
    version: main
- name: Trigger ffshmon regularly
  ansible.builtin.cron:
    name: "Execute ffshmon"
    minute: "*/30"
    job: "python3 /opt/ffshmon/wireguard.py {{ ffshmon_mail }} {{ ffshmon_pw }}"
