- name: Install curl
  ansible.builtin.apt:
    name: ['curl']
- name: Create log directory
  ansible.builtin.file:
    path: /var/log/ffshmon
    state: directory
    mode: '0755'
- name: Clone ffshmon repository
  ansible.builtin.git:
    repo: https://github.com/ffsh/ffshmon.git
    dest: /opt/ffshmon
    force: true
    version: main
- name: Trigger ffshmon regularly
  ansible.builtin.cron:
    name: "Execute ffshmon"
    minute: "*/30"
    job: "python3 /opt/ffshmon/wireguard.py --user {{ ffshmon_mail }} --password {{ ffshmon_pw }} --log /var/log/ffshmon/ffshmon.log"
