- name: Install network tools
  ansible.builtin.apt:
    name: ['bridge-utils', 'ntp', 'net-tools', 'iptables', 'bmon']
- name: Enable IP forwarding
  ansible.builtin.copy:
    src: templates/forwarding.conf
    dest: /etc/sysctl.d/forwarding.conf
    mode: '0644'
- name: Migration Step remove network configuration
  ansible.builtin.file:
    path: /etc/network/interfaces.d/60-ffsh-init.cfg
    state: absent
