# TODO check if fastd is already installed to speed up
- name: Enable buster backports
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '# deb http://deb.debian.org/debian buster-backports main contrib non-free'
    line: deb http://deb.debian.org/debian buster-backports main contrib non-free
  when: not ansible_check_mode
- name: Update apt cache
  apt:
    update_cache: yes
  when: not ansible_check_mode
- name: Install fastd
  shell: |
    apt install -t buster-backports fastd
  args:
    executable: bash
  when: not ansible_check_mode
- name: Add ffsh system user
  user:
    name: ffsh
    system: yes
    create_home: no
# this is not allowed maybe wirte a script instead
- name: parse interfaces
  set_fact:
    internet_interface="eth0"
#  when: hostvars[inventory_hostname]['ansible_{{ item }}']['ipv4']['address'] == ansible_ssh_host
#  with_items:
#    - "{{ ansible_interfaces }}"
- name: Please check
  debug:
    msg: "Will asume that your interface to the internet is {{ internet_interface }} please check /etc/fastd/ffsh/fastd.conf"
- name: Create directory
  file:
    path: /etc/fastd/ffsh/
    owner: root
    group: root
    mode: '0644'
    state: directory
- name: Create fastd config
  template:
    src: templates/fastd.conf
    dest: /etc/fastd/ffsh/fastd.conf
    mode: '0600'
    owner: root
    group: root
- name: Install git
  apt:
    name: git
- name: Clone Gateway repository
  git:
    repo: https://github.com/ffsh/gateways.git
    dest: /etc/fastd/ffsh/gateways
- name: Adjust permissions of gateway directory
  file:
    path: /etc/fastd/ffsh/gateways
    owner: ffsh
    group: ffsh
    mode: '0644'
    state: directory
- name: Enable sytemd service
  systemd:
      enabled: yes
      state: started
      name: fastd@ffsh