- name: Enable bullseye backports
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '# deb http://deb.debian.org/debian bullseye-backports main contrib non-free'
    line: deb http://deb.debian.org/debian bullseye-backports main contrib non-free
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
- name: Install fastd
  ansible.builtin.command: apt install -t bullseye-backports fastd -y
- name: Add ffsh system user
  user:
    name: ffsh
    system: yes
    create_home: no
- name: Create directory
  ansible.builtin.file:
    path: /etc/fastd/ffsh/
    owner: root
    group: root
    mode: '0645'
    state: directory
- name: Adjust fastd permissions
  ansible.builtin.file:
    path: /etc/fastd
    owner: root
    group: root
    mode: '0645'
    state: directory
- name: Create fastd config
  ansible.builtin.template:
    src: templates/fastd.conf
    dest: /etc/fastd/ffsh/fastd.conf
    mode: '0600'
    owner: root
    group: root
- name: Create tmpfiles.d
  copy:
    src: files/fastd.conf
    dest: /etc/tmpfiles.d/fastd.conf
    mode: '0644'
    owner: root
    group: root
  notify:
    - Run systemd-tmpfiles
- name: Install git
  ansible.builtin.apt:
    name: git
- name: Clone Gateway repository
  git:
    repo: https://github.com/ffsh/gateways.git
    dest: /etc/fastd/ffsh/gateways
    force: yes
    version: master
- name: Update the gateways via cron
  cron:
    name: "Update gateways"
    minute: "*/15"
    job: "cd /etc/fastd/ffsh/gateways && git pull -qpf"
- name: Adjust permissions of gateway directory
  ansible.builtin.file:
    path: /etc/fastd/ffsh/gateways
    mode: '0765'
    state: directory
- name: Copy iptaples script
  ansible.builtin.template:
    src: templates/iptables.sh
    dest: /etc/fastd/ffsh/iptables_ffsh.sh
    mode: '0700'
    owner: root
    group: root
- name: Enable sytemd service
  systemd:
      enabled: yes
      state: started
      name: fastd@ffsh