- name: Check if the defined fastd version is installed
  shell: |
    fastd -v 2>/dev/null
  register: fastd_version
  ignore_errors: yes
- name: Update apt cache
  apt:
    update_cache: yes
  when: fastd_version.stdout != fastd_target and not ansible_check_mode
- name: Install fastd
  shell: |
    apt install fastd -y
  args:
    executable: bash
  when: fastd_version.stdout != fastd_target and not ansible_check_mode
- name: Add ffsh system user
  user:
    name: ffsh
    system: yes
    create_home: no
# this is not allowed maybe wirte a script instead
- name: parse interfaces
  set_fact:
    internet_interface="eth0"
#  when: hostvars[inventory_hostname]['ansible_{{ item }}']['ipv4']['address'] == ansible_ssh_host
#  with_items:
#    - "{{ ansible_interfaces }}"
- name: Please check
  debug:
    msg: "Will asume that your interface to the internet is {{ internet_interface }} please check /etc/fastd/ffsh/fastd.conf"
- name: Create directory
  file:
    path: /etc/fastd/ffsh/
    owner: root
    group: root
    mode: '0645'
    state: directory
- name: Adjust fastd permissions
  file:
    path: /etc/fastd
    owner: root
    group: root
    mode: '0645'
    state: directory
- name: Create fastd config
  template:
    src: templates/fastd.conf
    dest: /etc/fastd/ffsh/fastd.conf
    mode: '0600'
    owner: root
    group: root
- name: Create tmpfiles.d
  copy:
    src: files/fastd.conf
    dest: /etc/tmpfiles.d/fastd.conf
    mode: '0644'
    owner: root
    group: root
- name: run tmpfiles.d
  shell: |
    systemd-tmpfiles --create
- name: Install git
  apt:
    name: git
- name: Clone Gateway repository
  git:
    repo: https://github.com/ffsh/gateways.git
    dest: /etc/fastd/ffsh/gateways
    force: yes
- name: Update the gateways via cron
  cron:
    name: "Update gateways"
    minute: "*/15"
    job: "cd /etc/fastd/ffsh/gateways && git pull -qpf"
- name: Adjust permissions of gateway directory
  file:
    path: /etc/fastd/ffsh/gateways
    mode: '0765'
    state: directory
- name: Copy iptaples script
  template:
    src: templates/iptables.sh
    dest: /etc/fastd/ffsh/iptables_ffsh.sh
    mode: '0700'
    owner: root
    group: root
- name: Enable sytemd service
  systemd:
      enabled: yes
      state: started
      name: fastd@ffsh