- name: Install isc-dhcp-server
  ansible.builtin.apt:
    name: isc-dhcp-server
- name: Clone dhcp-static repository
  ansible.builtin.git:
    repo: https://github.com/ffsh/dhcp-static.git
    dest: /etc/dhcp/dhcpd-static
    force: true
    version: master
- name: Update the dhcp static file via cron
  ansible.builtin.cron:
    name: "Update dhcp static"
    minute: "*/15"
    job: "cd /etc/dhcp/dhcpd-static && git pull -qpf"
- name: Create dhpc.conf file
  ansible.builtin.template:
    src: templates/dhcp.conf
    dest: /etc/dhcp/dhcpd.conf
    mode: '0600'
    owner: root
    group: root
- name: Change interface
  ansible.builtin.lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: 'INTERFACESv4=""'
    line: INTERFACESv4="bat0"
- name: Create systemd directory
  ansible.builtin.file:
    path: /etc/systemd/system/isc-dhcp-server.service.d/
    state: directory
    mode: '0644'
    owner: root
    group: root
- name: Change dhcp service
  ansible.builtin.copy:
    src: files/isc-dhcp-server.service
    dest: /etc/systemd/system/isc-dhcp-server.service.d/override.conf
    mode: '0644'
    owner: root
    group: root
- name: Enable and restart service
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: true
    state: restarted
    name: isc-dhcp-server
