- name: Install wireguard and resolvconf
  ansible.builtin.apt:
    name: ["wireguard", "resolvconf"]
- name: Setup wireguard config
  ansible.builtin.template:
    src: templates/exit.conf
    dest: /etc/wireguard/exit.conf
    mode: '0600'
    owner: root
    group: root
- name: Start and enable wireguard service
  systemd:
    enabled: yes
    name: wg-quick@exit
    state: started