- name: Install admin tools
  ansible.builtin.apt:
    name: ["netcat-openbsd", "jq", "htop", "rsync", "unattended-upgrades", "apt-listchanges"]
- name: Activate unattended-upgrades
  ansible.builtin.shell: |
    echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
    dpkg-reconfigure -f noninteractive unattended-upgrades
  register: my_output
  changed_when: my_output.rc == 0
- name: Copy README.md
  ansible.builtin.copy:
    src: files/README.md
    dest: /root/README.md
    mode: '0640'
    owner: root
    group: root
- name: Copy fix-batman.sh
  ansible.builtin.template:
    src: templates/fix-batman.sh
    dest: /root/fix-batman.sh
    mode: '0740'
    owner: root
    group: root
