- name: Install admin tools
  apt:
    name: ["netcat-openbsd", "jq", "htop"]
- name: copy README.md
  copy:
    src: files/README.md
    dest: /root/README.md
    mode: '0640'
    owner: root
    group: root