- name: Install admin tools
  apt:
    name: ["netcat-openbsd", "jq", "htop"]
- name: copy README.md
  copy:
    src: files/README.md
    dest: /root/README.md
    mode: '0640'
    owner: root
    group: root
- name: Copy fix-batman.sh
  template:
    src: templates/fix-batman.sh
    dest: /root/fix-batman.sh
    mode: '0740'
    owner: root
    group: root