- name: Install admin tools
  ansible.builtin.apt:
    name: ["netcat-openbsd", "jq", "htop", "rsync"]
- name: Copy README.md
  ansible.builtin.copy:
    src: files/README.md
    dest: /root/README.md
    mode: '0640'
    owner: root
    group: root
- name: Copy fix-batman.sh
  ansible.builtin.template:
    src: templates/fix-batman.sh
    dest: /root/fix-batman.sh
    mode: '0740'
    owner: root
    group: root
