- name: Install radvd
  ansible.builtin.apt:
    name: radvd
- name: Configure radvd
  ansible.builtin.template:
    dest: /etc/radvd.conf
    src: templates/radvd.conf
    owner: root
    group: root
    mode: '0644'
- name: Restart radvd
  ansible.builtin.systemd:
    enabled: true
    state: restarted
    name: radvd
