- name: Install radvd
  apt:
    name: radvd
- name: Configure radvd
  template:
    dest: /etc/radvd.conf
    src: templates/radvd.conf
- name: Restart radvd
  systemd:
    enabled: yes
    state: restarted
    name: radvd