pool debian.pool.ntp.org iburst

# Serve time to all Freifunk client segments.
allow 10.144.0.0/16

# Keep serving local time if upstream NTP is unavailable.
local stratum 10

driftfile /var/lib/chrony/chrony.drift
rtcsync
makestep 1.0 3

logdir /var/log/chrony