- name: Install fail2ban and rsyslog as dep
  ansible.builtin.apt:
    name: ['rsyslog', 'fail2ban']
    update_cache: true
- name: Copy fail2ban config
  ansible.builtin.copy:
    src: files/jail.local
    dest: /etc/fail2ban/jail.local
    mode: '0644'
- name: Restart fail2ban
  ansible.builtin.systemd:
    enabled: true
    state: restarted
    name: fail2ban
