- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present
    update_cache: true
- name: Configure Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: "0644"
- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
