grafana_apt_key_url: https://apt.grafana.com/gpg.key
grafana_apt_keyring: /etc/apt/keyrings/grafana.gpg
grafana_apt_repository: "deb [signed-by={{ grafana_apt_keyring }}] https://apt.grafana.com stable main"
