- name: Install dependencies for batman-adv
  ansible.builtin.apt:
    name: ['linux-headers-generic', 'libnl-3-dev', 'libnl-genl-3-dev', 'libcap-dev', 'pkg-config', 'build-essential']

- name: Download batman source
  ansible.builtin.get_url:
    url: "https://downloads.open-mesh.org/batman/releases/batman-adv-{{ batman_version }}/batman-adv-{{ batman_version }}.tar.gz"
    dest: /opt/batman-adv-{{ batman_version }}.tar.gz
    mode: '0644'

- name: Unpack batman-adv
  ansible.builtin.unarchive:
    src: /opt/batman-adv-{{ batman_version }}.tar.gz
    dest: /usr/src
    remote_src: true
  when: not ansible_check_mode

- name: Delete batman-adv archive
  ansible.builtin.file:
    path: /opt/batman-adv-{{ batman_version }}.tar.gz
    state: absent

- name: Configure DKMS
  ansible.builtin.template:
    src: dkms.conf
    dest: /usr/src/batman-adv-{{ batman_version }}/dkms.conf
    mode: '0644'
  when: not ansible_check_mode

- name: Build and install batman-adv
  ansible.builtin.command: "dkms install -m batman-adv -v {{ batman_version }} && modprobe batman-adv"
  # notify: restart batman
  changed_when: false
  when: not ansible_check_mode

- name: Add batman-adv to modules
  ansible.builtin.lineinfile:
    path: /etc/modules
    line: batman-adv
  when: not ansible_check_mode

- name: Check if batctl is already installed
  ansible.builtin.stat:
    path: "/usr/local/sbin/batctl"
  register: batctl

- name: Check batctl version
  ansible.builtin.shell: |
    set -o pipefail
    batctl -v | awk '{print $2}'
  args:
    executable: bash
  when: batctl.stat.exists
  changed_when: false
  register: batctl_version
  check_mode: false

# no error
- name: Set batctl_version to stdout
  ansible.builtin.set_fact:
    batctl_version: "{{ batctl_version.stdout }}"
  when: batctl.stat.exists

- name: Download batctl source
  ansible.builtin.get_url:
    url: "https://downloads.open-mesh.org/batman/releases/batman-adv-{{ batman_version }}/batctl-{{ batman_version }}.tar.gz"
    dest: /opt/batctl-{{ batman_version }}.tar.gz
    mode: '0644'
  when: batctl_version != batman_version and not ansible_check_mode

# TODO what about the old version

- name: Unpack batctl
  ansible.builtin.unarchive:
    src: /opt/batctl-{{ batman_version }}.tar.gz
    dest: /opt
    remote_src: true
  when: batctl_version != batman_version and not ansible_check_mode

- name: Delete batctl archive
  ansible.builtin.file:
    path: /opt/batctl-{{ batman_version }}.tar.gz
    state: absent

- name: Build and install batctl
  ansible.builtin.shell: |
    make
    make install
  args:
    chdir: /opt/batctl-{{ batman_version }}
  when: batctl_version != batman_version and not ansible_check_mode

- name: Delete batctl direcotry
  ansible.builtin.file:
    path: /opt/batctl-{{ batman_version }}
    state: absent

- name: Remove old batman-adv versions
  ansible.builtin.script: files/cleanup.py {{ batman_version }}
  args:
    executable: python3