- name: Install basic packages
  ansible.builtin.apt:
    name: dkms
- name: Check for currently installed batman-adv
  ansible.builtin.shell: |
    dkms status batman-adv | egrep 'batman-adv, ([0-9]+\.[0-9]+(\.[0-9]+)?), .*: installed' | cut -d, -f2 | awk '{$1=$1};1'
  args:
    executable: bash
  register: installed_batman_version
  when: batman_version is defined
  changed_when: false
  check_mode: false

- name: Print batman version and target
  ansible.builtin.debug:
    msg: "Currently installed batman {{ installed_batman_version.stdout }} target is {{ batman_version }}"

- name: Check if batman-adv needs to be installed or upgraded
  ansible.builtin.include_tasks: from_source.yml
  when: installed_batman_version.stdout != batman_version
