- name: Clone  ffggrz/ext-respondd
  git:
    repo: https://github.com/ffggrz/ext-respondd.git
    dest: /opt/ext-respondd/
    force: yes
    version: master
- name: Copy systemd job
  copy:
    remote_src: yes
    src: /opt/ext-respondd/ext-respondd.service.example
    dest: /etc/systemd/system/respondd.service
    mode: '0644'
    owner: root
    group: root
- name: Copy config
  copy:
    src: files/config.json
    dest: /opt/ext-respondd/config.json
    mode: '0644'
    owner: root
    group: root
- name: Copy alias
  ansible.builtin.template:
    src: templates/alias.j2
    dest: /opt/ext-respondd/alias.json
    mode: '0644'
    owner: root
    group: root
- name: Install python3-netifaces and ethtool
  ansible.builtin.apt:
    name: ['python3-netifaces', 'ethtool']
- name: Systemd set up respondd
  systemd:
    enabled: yes
    daemon_reload: yes
    state: restarted
    name: respondd