- name: Clone  ffggrz/ext-respondd
  ansible.builtin.git:
    repo: https://github.com/ffggrz/ext-respondd.git
    dest: /opt/ext-respondd/
    force: true
    version: master
- name: Copy systemd job
  ansible.builtin.copy:
    src: files/respondd.service
    dest: /etc/systemd/system/respondd.service
    mode: '0644'
    owner: root
    group: root
- name: Copy config
  ansible.builtin.copy:
    src: files/config.json
    dest: /opt/ext-respondd/config.json
    mode: '0644'
    owner: root
    group: root
- name: Copy alias
  ansible.builtin.template:
    src: templates/alias.j2
    dest: /opt/ext-respondd/alias.json
    mode: '0644'
    owner: root
    group: root
- name: Install python3-netifaces and ethtool
  ansible.builtin.apt:
    name: ['python3-netifaces', 'ethtool']
- name: Systemd set up respondd
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: true
    state: restarted
    name: respondd
