- name: Install bind
  ansible.builtin.apt:
    name: bind9
- name: Adjust configuration options
  copy:
    src: files/named.conf.options
    dest: /etc/bind/named.conf.options
    mode: '0640'
    owner: root
    group: bind
- name: Add local zones
  copy:
    src: files/named.conf.local
    dest: /etc/bind/named.conf.local
    mode: '0640'
    owner: root
    group: bind
- name: Install git
  ansible.builtin.apt:
    name: git
- name: Clone bind respository
  git:
    repo: https://github.com/ffsh/bind.git
    dest: /etc/bind/zones
    force: yes
    version: zones
- name: Restart bind
  systemd:
    enabled: yes
    state: restarted
    name: bind9
- name: Update the bind dns zones via cron
  cron:
    name: "Update dns zones"
    minute: "*/15"
    job: "cd /etc/bind/zones && git pull -qpf && systemctl reload bind9"