- name: Install bind
  ansible.builtin.apt:
    name: bind9
- name: Adjust configuration options
  ansible.builtin.template:
    src: templates/named.conf.options
    dest: /etc/bind/named.conf.options
    mode: '0640'
    owner: root
    group: bind
- name: Add local zones
  ansible.builtin.copy:
    src: files/named.conf.local
    dest: /etc/bind/named.conf.local
    mode: '0640'
    owner: root
    group: bind
- name: Install git
  ansible.builtin.apt:
    name: git
- name: Clone bind respository
  ansible.builtin.git:
    repo: https://github.com/ffsh/bind.git
    dest: /etc/bind/zones
    force: true
    version: zones
- name: Restart bind
  ansible.builtin.systemd:
    enabled: true
    state: restarted
    name: bind9
- name: Update the bind dns zones via cron
  ansible.builtin.cron:
    name: "Update dns zones"
    minute: "*/15"
    job: "cd /etc/bind/zones && git pull -qpf && systemctl reload bind9"
