name: Ansible Lint # feel free to pick your own name

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Ansible Playbook
        uses: ansible-actions/ansible-lint-action@v1.1.0
        with:
          target: "setup.yml" # specify your playbook file here
